apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:vnsyEbWh2/Dz5m+Z3/JaiLpSz0xsFn14Nx8Ncl6hmQQv7dmF,iv:93Onm9dKBB0kK3J4WIEnR8hdTcgKG95UWnYgTIFD9Ro=,tag:d18wLmRIGT3bY/ztyBZeRA==,type:str]
    credentials.json: ENC[AES256_GCM,data:eX21gMMPPUtQXwCkM5nOCrBF8XOv18O8oBOgutc+h5/JSLWqWNqV1f0xsCQZCe4WhZMRMsOb0nNj2MGT0L+94h6eKBqmLMgcpvQD7RQPESLMd29IzJUtuHPtA7fkw0ctPsU/JvAsrQjVdJAL81AC/R8MQ2O7b8/dguDHB8vTmN83kY1GNdcMX8PGExNGUkKwQpTjeQqhj99snHfe4bKx3tw+0e514LHHXH9vaeI4kA==,iv:jbJOMkuMheRhEnKGmR5VC/7yuVvNNcIWbs7d2oHuG6g=,tag:RVVlY38uqMZcYiv++EANjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSjVwYnJxZ3ZRcUorRWp5
            UGtwYklyVktwT0w1a2x5M3ovWmJUSHBNU1VRCmgzaGRpaitIQ2Eyd1dwaVovU0Z4
            b2NKNFh5TG9taHRoN1pPMWJxRzg3Vk0KLS0tIG9uMkJlR2RHd2V6OVNGZWYwekRH
            TjlVZXk0SnF3eWRBZTVSSzZlblJWQUkK3lUle90IcZxGuUGiKQhF7ZUEH3wClJ2H
            8dHubhKqFF3OB1I/OOezKCinNB32coJ0zphzDxqI2CqcF71OGXlx0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T09:20:20Z"
    mac: ENC[AES256_GCM,data:sTcmRUhA6LWiR51fkCv/9agXqDr4V8qS0/u9KTOMsfrNP7ilpR1F22jlMkKSBJyDSW0VZNIp5Aflf8gUGzrDc6XpjI/PkhhkSGG9FX2z0y69D8fxztqX+tQ7IQpkUVVDez2QGWBAWvOERBwQRR9qvaHayyxZYHDbaDMKdnuaOv4=,iv:pz75UiycF4RQUq+prniULWvHku3TPji0TBkAX9GhP/w=,tag:qdLnnEwNxzd7OXkQh4se+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
