apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:KkBsyy0GS4lX45GbnXB+30DgpW9H0D0mEMdA91zKhfQTlVYF,iv:sJjwPP6upGpVsGTc9tJzo//WflrkV8ZsOq8fvOD0xoo=,tag:F1pyexsrm00/UfWCLZLvqQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:n94bL40AD/8oI5TAzx/fHdGWFVA9un3LJJnft6hDaWXPSKqXdCmBtDBUwuDf2UavLBSTeJb7xH0LMG1rzZKA3DslsdMvaDATPAI+2HHid+yDGN37ShIH3pBATwvbiiKNAFIysZb5YxAh1iWb9CXlmtPmAm5aD/QhD2VzDE/pVFNuEictteNlE4Sc7vJpDjsb86snhvdDt0A/6rIfx5E6SYREwC4/7cqj/QDsQU166g==,iv:Wkgnrjzl4g/hT6c2qV/UuPdhYsn7DHN8OINvHMZ0BxM=,tag:Mx3fUPzI19ZJbtLe/OuiIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYzF6SnBnNERTelRVN3Ni
            eURBNTJEcitPT0VMUWgyRjRFRlRJbEpzZDMwCjFqZXgwVTFIbjBCVFdlN1VHemhy
            RkNCZS9tU3crWlMrc1hzallDUDRDSzQKLS0tIHlyNjUrcFdRUUJkcW1KM3NKOFlV
            Z0ZVem40UzA4aFE1a2RCd003cU5UanMKz80JqdC9SUBBm8ykgwyeHfL8dbSUjC67
            J2OhZxWahChAnNCAEXLCpn30GTBDlMX3y2QnnzqWeae+ArHYjeU5VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T07:07:13Z"
    mac: ENC[AES256_GCM,data:iH9TRy3BspYjQfv8c1qec6J6Ga2KyMFORwMx+up33rTohroYt1onDyNaACHTR7L+rpK2a0k9ni0kt5PN5/kvJsZrRAia7M544wSHXOabCiZHFu0p6vL/ncBX6pNUM1RXFbbY1IYhry3wKOZuFSygMGTJ//epw7dC3HcmmfCEnP8=,iv:RyX4yMtObn4sk+nNvi5AndxXuIbzjiCVW+FeDftyl4Q=,tag:/WEPm1YV8UruoXlKLCr4wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
