apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:bDhR2FZPhEkZ08fw99XENGaZJ9y0oMvLFsYWM5w323vKXm/W,iv:ZRS5mNJKm7PZCLwcciI3vEpfPs44fIvPI2gC367LQZI=,tag:UP+MfZNFqfXhK2hU61jvKQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:raq6vwddLcDkebH2URUAuW2aH3HRGiDNreiXV0N2zXfANILzaWdMxEPdSjNT0fQ5JaHujiMOeU/RwiG+FTO7Vykq8qGZmWkB6HFk4G3joM6AeYepBoiYzWosjydy13iGMXAvqAqWbfhhbuA69RlUuTAJqo17bhSWIT/esw+CsXAAkij8TWmiY7TiqXdfLAMhV8gJZ5equZWaLZGQT5Jd1NvmHTSrYFYqPC+6P93qfw==,iv:5zMaFjNjIZ6EMfBjaP1TCcFGWkO009Ye/C4NWl9nhmk=,tag:HQ5wgy9w+7eLt66WsOR0ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YmFLc1gwc2w3L3VVU00y
            VGV1REhycEhpaGdCTFpseWt6bjZuMGdWYWg0CnJ4RTkvei8zL0FMN0RWVDdZMWRG
            SktyaWxhaU1rTFdDRkxvajR6bVl1TEUKLS0tIFpMd1kvQUpZMm9IWDE5eGhZT0Fk
            NEs3clRUbzMyZml1Y3RCZ1VKZnpHWjgKia2Lp9Yk7/1a66uHBBj+sWmICg0vL/rU
            mBuqwNuiGGmjzWVIChbfhhcmKMJXE2NQ3QBr45yQ5i8WfoCDRzEqGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T09:14:24Z"
    mac: ENC[AES256_GCM,data:iisP4XPMBdgA2RLyNQ3lEsLwSQz6Nyhajo4ethiDHmSyhoNu0vvUjOBsHyjs5y7+XMGmhyGoRP8N54jBvP/KxjtOFz79RnCm3P1isl+BhSDV2vqccfIFhH2ZXJ+8PONO3lcD6S80qVJ1jXI3QZdboriFE5i8fO/XviHS2wHtrhc=,iv:fZfKNkv5Ck1hDWauie4Hi/MyTYPJpHAjLMUnpuVn4Rg=,tag:bado9oJ15tYFGk1GJYwCHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
