apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:OGrsBqJuUJpWFtW+4vKUVBShz1LeNd5QQhl+a6YE5MSIU0z8,iv:/tGths+6l0xaAR3byTL25ruD4knCizhune5a3wmnGRk=,tag:97eRJ9fnoYaHkfRsRey70Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:GofXcFi2RUBG1lIbLRq8qCCfvKG5ntsoYrO9x9pBVQmxm8aWeYChyGbeB/ttuwn2iHSZGNzxcAzShBftvrxotYE+sNlBa5yJr/elrSsEj3YIALm6/A43K8fbOXbj4lgZMTBMYx9O20r0PPwgbJuqZPHulH/3sXzwFCK49Gpzkjdt8mFpu4EnhS8v47uOLuOhvEE5Yg8k21/SB1VAM8fJZliGsiWa3V+0yxtFvypWKA==,iv:hYHqCOAgRIahcziaVlJl28KDhLF2s6SShhSkQ2nCkUc=,tag:pUgLUGP1JjLMjd1xHSyziw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0akg1bGtaQktUbnlIMDBj
            eHVVODJkVWUvcE5ON2VTM3FXc0t5WUtmb2xnCk1JWklxaDN6VEgxVmNkbFk2dkI4
            b3F0TDRuMklSb0VOVE40akRxV3Y4OUkKLS0tIHMwc1ZubXpQZUUwN2NUTmdwOGJa
            em1hVHZlM1phRHMydE1oZEZCMVdvMk0KKdlW5xBHDs1GRGcBrZSZYgWx7PhrcQ0j
            cnCWZUxgUjIjM54e7Gkslq4Gfef0gpdbJrjpFSxYbO3aPxZxU/ltEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T06:01:38Z"
    mac: ENC[AES256_GCM,data:6xW8dRc9wLnp8XQucGg4if/JGd/fiCwuj+LMq1na9w4Ddz+tXHwHFSW/b4KoJTEabEMSuKGwgHiRvTAcZbzPOUfjWj4iiu5i96hhCdPFviGrY6MOV6FcwYLpvck97uTlUZSw32cSZN54VyS6z1cWT4OOUVp8flSFANJ/rwonL1w=,iv:Jc3y0m8OgzHUeUduXX+0bGAbILMRmAYLFO/HecYH7ZU=,tag:WTUQ11e2XLgRP62T/zaqTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
