apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:I9nU524GcgMS3VSPyO5pT5xYz8kl3ccMoZWSqnApSFhslh4REr+pIg==,iv:MzT00k4fnXBTUmQkyGkOZj9yxZpBU8IKcbaAZgODvKY=,tag:JpkjFutqUok8Z6EOIE4+vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT2p0WjY0emhETENVUUl4
            NmVGK0M3dmdrOENaWWZJZlF0QjUrWVRpZWtFCmhtdXI5dVhEUzkvaUlRMURQM2Ny
            SWN3ZjhVdkNPSXBHTlpVdGppU0s4am8KLS0tIHl1NTVBOHZmM2V3emxKczkzUm1I
            c2ZLMW1ueU5aQ0RmYWpCdWVncThnVEkKbknr0jM+pWeADiSSgOBn5LP69MhFf5Dm
            MM9TeJ2ZVG5OBe7UzAHuQguKUnc7q+j1J3HkMvVygCpASrTW8fT8HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T08:34:05Z"
    mac: ENC[AES256_GCM,data:xIEfmX1WLZ0ahVgLzcr4wcZoTW7AUbFUYqZpGSLPEROYPyXJmGNep08+LexLJkjiHOrIbScvxVjWOLNS3uvZaIxHAgCTlwfTv0XJMOkKAkFMJZ2w/cWKwYRq3V87tCosMacNu3YkdUDH5rsjQyxmk2S/kAL85Gb2CP4m6stlcGQ=,iv:bRhAA3++yw9NHYx3hFsXYVkJdjofuD+soy6gGHWY6BQ=,tag:pafsjkKKBFtDroIfFYl2XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
