apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Ln5tZnnQKDazJBK9PWl2AX8c3/VKplSlNTGTVEN3NtrA26fvccU/XQ==,iv:kvP/1zzqqUpZ6X0j75arBFdG4ZcRRAos3+wkU0lqQQY=,tag:qH80uXmy09Y3n44T69pfWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTG5sN3RMdjVETm10aXBX
            Q3cyL3laaVV1OCszTmRXbUI3QmkxTlhLeFdjClYyZkpGTldHRzBFQTQ2YW9EL09J
            eEhIS0VmVHNpNGwzUm1pVUxHYWRVSXcKLS0tIEgzRFp6OHJQK3JHNk5jeDc0cngw
            V1NMZFliZFhXNVQvMktqckZqT1JBek0KcWOoFjjAQysXrmRBADSaKP9RwtUaArbC
            so92v64B1M6y+M+h2weC4kPm54UppVnMg1uIdTDEqazZvgkjiHl+vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T11:10:11Z"
    mac: ENC[AES256_GCM,data:/RUM1WPfvUsxvaa8Cs7nW9aG3spdBvGEgZ74arTF3Lus283yMiV1dSP+RoxGFLDCuy7xL+8lMGBnk6ZQ9O8fIY0kuwN+sVQcb/TVmgkCB0rWgoIfqxPm/jIc2KdRXP9v2qwXdKljrYH617KiDW2NNdeaiYSz0jsesr9qCOfT5S8=,iv:YrmU8BZEYh92wWa8syvJ3J4VPiVlLKHFm+TdFqQmWLI=,tag:R7LuJ4l82Fc1dyBqJowK5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
