apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:R9XDJLNLiAIJ4t8bSbDfA0/ponuDq2KnVPEHLmfeA8EyTVFi0gnOWg==,iv:EYutRBkkapfiftldT1Lk5mOlZqLR4DoXSAjkFvSzU2Q=,tag:+RfXfopPXN8h14uOiSXrhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR1hPcnhiWEhzM0VJWFZu
            aGFrSlBMc1NRUlBkU1lVVXNvMS80N1l0YVVrCk1xTkZ6RThuWjczZ215dGoySDhz
            V1lFNllyNUJ4WHliWjg3S0NZeFFucTgKLS0tIHNmbjZKcUVIQ3dBK0wvZTJTUDFK
            cHkxSXV5ZTZaSFRLWlFjYmtOMFB5bmcKPXRI5ZuZiLMIiTAleWmVrlaJtOaxMY6g
            4zeCWsiTCYCrtYf6ouqzeK5KaiTlCbxU2yJGBppievEYyWNAyMT+6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T16:18:40Z"
    mac: ENC[AES256_GCM,data:o/XEfPHoojX+WhuOzfFCBapPKztc+zjs7YR/N8qqDrJkGP68QZmXQiiJOIjCX5D2n7UogwaG0RcN3meRdU4fgoh72NDCtOU74UfgESQQzbwtC1UOYw18f9sL2F3zOwi84pUhNeNbaVIlOFy7XlA0oS9aIebnfI4iQV8Xu3Kmw+k=,iv:oqbHYFrFMsPzxWgx+5/QpgII8Pbd77IQPUqPbL8qtOw=,tag:SHgUKXRDGOjtm9jGVPc6qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
