apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:vuvcgEwXA9Y435kdS3FcznZjoO0zyAAFBlmwnxDVRGwC02OITGWS7w==,iv:Besoh8xPzaeDtPa/pLj7luRWy1w6xVyd9NRgjmWdnm0=,tag:G0MzmntucTvYlAGapkmpoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMlh0dEZ0VzMyUVJKSEJN
            ek9KTXJpdHVhak9aQ01ZdVpqRzRIb01wWFZNCk1PKzRoY1RFeGxPMnk5QkZ4WWdP
            Si9Md3NLS0ZNaXZ5ZzVGR3JhMWZXcTgKLS0tIDVkd3pSd2VaRW03QWxlZlREajRs
            elpBNHlTOU50d1grSGd4bDdCaU1YdmsKpxMagOfs/Vo8KiqvMHq2r/+X1V/0U98y
            VWgJ1+M0fttJCU8t7Jl9uH/CPFJPFTcSXYn88Ranx3Y4zSlWgtPBwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T08:47:01Z"
    mac: ENC[AES256_GCM,data:bz09eWLQH3G2sOa+J9F0YVv/8eR1+Ydd9NgBmIDiZofGYKQhBDuR0s/tSVmor/ITvop5mLgyc1+ZgeCi+h8JPYIXrkwkSq1isjYbcexTkG6AwcjfMrkBU1Q/oQfdLpaqpjHydbnafXy+yIRoLKSMKsvzmLvPykAzvUg2V+eRpSM=,iv:0j57eZO9rODsep04DLj9YrPXCc0bjW8Mxf+c1jXzuY8=,tag:yJldzfF6QcM6gfSSN+DC+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
