apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:IsMyumBEICNJZETTnLRjN/pLG8qxkQ8G7ciyOKTmss+ld8O0knfyeQ==,iv:yRMd3sgcYjMQMJlufdu+8wc9hi9PlwKo9xpHAk82bAM=,tag:I3ylEbd0MaqzOlqg4gG4GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaDhVbWNXS0xuNkdhMFpX
            cVcvVG96QitLdDUvcDdYVWVVU2FLZDQvUWdFCk9PZmsxc1hHOTFMaU5NcUo5Wmtt
            OVVXN0FQdXFHSnl0VTVCazZodzFQYUEKLS0tIFhuY3NvdU9zWWFBdjUrZ1F3enEr
            a2U4M1pjUHpBbVRZdkxRc2NWUXFyOUkKzdydN27PAoUVb9S5O77K0ZbFj8XU4d/8
            KCOF/mI4dPtLFkpx0u0QRYCrOdgVCKPVyXnSdtepAue/PvzsEadAtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T05:53:26Z"
    mac: ENC[AES256_GCM,data:rmL1kMnmnaRrmxfOQQPWt/ygMJDUi+Tdmiv+fwMpOXZcXRyXo5qHeBCwGzqgJ9W/cYTAeMp+OLzVhOQjkuSU6Fr/NZ1r15omN/0F+bqbfbWYtEaqB+gJEjgqhFRJOvUVazszxd4/NuxJMtGSm5te3/7lHC85PehjEGqnvtFb55w=,iv:Bt7txrZnflIf3S82r79ift1OKjbpUvrj58k014zNeuA=,tag:ilp3Db2sqjUvjauEyCNywQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
