apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:QKbJjt5nDPEE9RyO/Vuz7mUuk1y9Eu5dwXxFScY0M446gFY0Gn6kxQ==,iv:pWgEqlnqn0aO7YdV4hdWp5hnxNIu9cX3UAPTci0sSfM=,tag:zvOu9LDwc1yJne7EU3k+3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dUdiZVdJS0R2STRMTWFW
            NVZWZElNV3FCVERac0FDMTFNVFljY0dIYXlNCjJMazlCWldkM0lOdDBTMlBKK2RD
            dHNZWnRWQkJGSFErTnVVS25EeFE2UjgKLS0tIGlNbGMxRDRIamtucmFnYlVNZGZl
            UEpwQlVYSmZXdTY1cFVuajhFaTlabGcKz68X/09ohJ5ebe7Cuqxsc4I2rQ2w2xp2
            AdgW7TqphcJnjk/DJWGz5nKcAbqvHEkIAy3raydMZitQiTJyk0FT8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T11:40:11Z"
    mac: ENC[AES256_GCM,data:k5Mz7HvIEKuRpy+8Rv7OM4bfggUtoPioFOXamaHvXn6ouLWW0XFSGlq1hNgIRVX4QwZ6tYJ4VSJjOnQ9O6/MJRYVwJunDpQA5N25m9EU+PcA51lmFmM91djXrmNBzvBa8pn+gc++ZWNZi0gWpDZWBrgqNQWMu+o086zC2jvmE1Y=,iv:UO1is9NzqDqjIcY0WjrzwTPKsbHgIpyZazLgQknoY3o=,tag:dWBOoJH3xSfoNMme9eCx6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
