apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:n56qlKqwa9chTgXqaNbVl9ucX6Dtr7a/eI+HwQQB8ud9rcImBP3/Pw==,iv:IVL8g8W0pnw+tNfPVxMRT+lEIh9lTH5HGGsiWqeTGac=,tag:6S9ftmOAT5g2t+GrQ7WRrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMFBqRllNY09jek9ETGo0
            SzZEOU9za1JYYWVwUzJFd0NEMVhVOUNpRjBFCjJtSzkrcy9yQnFRWjRHZElxQ2NB
            U2lBNnBvSVBDSHBFNzQ0TFhJQjdvdlUKLS0tIGlCUVA3NkYwMy9XNGpuMkFvVXJX
            cFhzUGxZVFZnekN0cmVpNCtEOUdTNzAKuXe1dx57uUXAD1OoWpUZTZQhfcvBX6aR
            UDaeclClOx0xk42WnHX13u7tHBJrNguKHTfIeyA+AfCwil7/XU7hNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T12:15:30Z"
    mac: ENC[AES256_GCM,data:bkG5dtgwpPKUWvgjhvFxNxF8DDFrTbmz4iRjWyPrOwOintkSJirEMudEPo1g4qkHu1lnNGiUQM9IuIEE0a3X81I4v2jE/c4sS+Yfd0QSp1zWYIUUyYDecob+n3rEwHSeWtWeRvuONrXWnwztVhXzUun1/DvGW1L63rU/gN4M8fU=,iv:cUs1fmyq6yCQSXp48kmE3oII+8h+A6IM1mRAYjMk4lM=,tag:50Gv+DXavI3pk5/m5GDzNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
