apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8eo21qr3cXIfj4zudlqRdLcKJ5M4bDY=,iv:ig5xztF6JOD+ynzZEaQg/mJlEaNmJOAgqtnk2PRDNKw=,tag:PKLnl0BrUaLnTy1hlU46hQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4+R2n9qlxq9zx701lbDDM77EWSs5uKXPfqHPUkXpFT9rjpFw,iv:v4CUeNWe05SkaqhOPXG5k3se/sISnuhUET0nR1cm2Io=,tag:KsHClVadTv3hcaHw04SVrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTTB0RThHR1I1VFJhTGY3
            SkNUenVadmFsWjJWWVAzYXNteEE4VFBFeVQ0ClZvRXZDcmZLM2dRZ1JxTlo4VVdL
            SnVhVUUySjV3aUV3Qmtta0N2cU5Qb1kKLS0tIHN2dDNBcTdRanVpRXk1WHVvYVRl
            RkpKTG45MVI5UDdidjRUQURvb3ZQZ3MKKv5Tj3/hGkznv1keN8b8L+RoAqOl2EAU
            viLWgsBk30wsTazfj7fXFXtVKJbuDRPMy1XNgHWBP8tkW/1ppwmr4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T09:20:19Z"
    mac: ENC[AES256_GCM,data:uJDYRYpLGFESqrGizXFXHwMnVSflCCtdvYnFf1kZaMraqIgtX1lT+xa8o05xY3NEJztNAJzPxrK52czoHk68Tqnhx4EHN5QgXrUM3UglUCL9uVpqEDN2fmr0DZtpFbfEcN1TM/NyF8byJWLzKEVIeA/kl98m6qhOnMvRpZVlgmw=,iv:Qg04CaoiVi0OQAzJeBZfH3/iVBBZCGDMva6Jhk/Bb5c=,tag:cOtN3RMKQCEQcZFmzGlpDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
