apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Zo0OJeus/Qa5Tba0C2/i20TzZh0PcY8=,iv:IXv5laaX1cbwkp6aZT9f2RARSxPfTmhpX6YJEE8a28I=,tag:MwCF+B7DuVvPDfpydqduUA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/AqSoJ9w3n6v1hPBm/kn8vBnZcrKh8ItWNsuDuY9ZH+GOi4p,iv:RV2LNNO224vi6b0+gnCH708jhVcDXg5e/pc4ZTgmF38=,tag:0nkQAHebw+iIKNHc9QkRiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWlJvdysxTUd1ZUxIajZi
            YnFHZVI1NEg2MC9zRnUxZ3VoU0RFNFJpeFNnCkZ0Yk9IVGZlUENpT2tLUXpocU5j
            T2UrSDNJeEpwcG1nWm5VM25qaTIrVTQKLS0tIEFzUmJxV3RLeTk4a3N0aDZoNFI1
            V2FHZDFZaUx0eFdXWExzS3JiNkR3UGcK6mflXJiAXLBtaW3WHlCWiSvBSGZgpZVR
            QCuEaEJKlExbmtQRk/hvByyQ8NCptGJb/BFSTKtPeZBjp05k5tj8bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T09:22:14Z"
    mac: ENC[AES256_GCM,data:r76F0b5GD7UmtGKJ/SNHwZzmgI5db+2A+T08t1tb/RXErGXu7ym4PYuNJb5DN6ak+pp0aMCNdYtgWvjMh4OWNkH+G613/h6d8UPBr2BZzXtbnpmI/wn41canpq8QBC2cVZju0q4XPtDzpHqjuIQ1UJEL6DNqQGgsCzC58yOD/d8=,iv:UtAoGTUA7C8grJzuSZXvGsxMNXstC4UnzmDIy+rQB50=,tag:qWYJ1UAqE7ZDf8vMSo0ZdQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
