apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QR2+jX3I32RgQL920hbTAsFLRmrDINU=,iv:qlkW+jTzLjqy84rwmjN+7LWZXJz7DB6YERK4OFY2+Kk=,tag:qzzxxzC0MH6j2MeMKOeCdQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5cv2Z2KyKfaN6BriVbs08dampBEEyO3V/sMWdAeHz60w+vBH,iv:eY+wO8bO+ywhWZF94Fqjijdi7vK1aTCwEv3kZiJwM98=,tag:joJB++T851XaQR7478VaWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WnNBSDEwUXpDeXhsamIx
            MmpENUtxNmY5cjFudEdNNW1ERlNpZEpQYno4CjE2NUl6RkFOakF6ZTl4Q2Y4NC80
            MDZCYnQ2bEpLSDZsbUZldmxuZFp2SnMKLS0tIFFWTWRzMERwcEo3c1JEVVR2OERX
            TDk4MC9KUnB5bmExem9UMXBpcVUyYVEKmLeNFRW6o8wZxzKil2vJgnkoVAaR/JhT
            BnEFZjF9gODY/723D0qhuY0q2iCdPqaFpuci6njiIkR03uril0xumA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T08:34:05Z"
    mac: ENC[AES256_GCM,data:S435VMLglcqKrs6VWUwjclqESKg2nL/7LeXKU3hE2FX1oo1hVPpb1jIxE1u/b/yDIXN3yf7IfC6abe5OrWyld8Af5mTEu/5DQclc4uXIRUufQ6jSry1WKk44X9iLsbQaPb+EpCt2Kw5QC0YOyGoTozWltwMDuv7mxD5q1uYQmOk=,iv:tAaHs2pBWugoUxdAmLSWOJoVKRjJ/fAGNyg1DnKYqKw=,tag:DcWIl7nWJloERv56px+hCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
