apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:REC+ZZJEtE/TqBk=,iv:vMYaJF3xsO01ki1gDW7qnKQgV7SMMLCrvqNOUDmsXRA=,tag:ca1XFzZeb373BXkx361wrA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ESDWvrB+2z5opW6PBiA2x3bfZfe/PnA=,iv:hC7imNb8GPxIMcpwVqwPI7Y3vvMiFEl4S8GnftpWGmg=,tag:frprYquAol8Tdo7lJBOAZA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AwFiYJHmPu2fX7i2zMLqpIa7+pgGfDCTB1ZLK9C8CIHG0AeE,iv:pi1Jq1waYa5PmlCQ660K6zHoMzrooBvFAc8WgpCouvo=,tag:kru31oRj56VgUe5iDY2SBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRjNiakJlWkV2MG5qcFpm
            UWxtTmgxN1BsY2g5M3l6SjVFYkgreG9tU25NCk9GaWU2N05iajFQOEVDUFM0OWla
            TnlsaG1nTHZRM0FQY2dzaFBIbnFmcXMKLS0tIFB6VXZSMitPZEVjVWVTWjcyRkJV
            anBYUVd6eFVuMGV5N25BcDJIaHY1K0EKWHJbtVqcDZmK7zvIyzrcezKaLnMs+nLz
            5iJ6IqXctTL9eLLuj04DbpC2sw4SkcDVA8EcPeN8GJitmY4D5kedLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T06:01:38Z"
    mac: ENC[AES256_GCM,data:fhvt6hHcXP0g0DQoWuk8y5HvrzbsUBLA0cC5ovqg1v2ru4rs2KFNmwQv272d5p6MGXhFFSmXtaIBhndBiMH9joEpg6rAP98QMMKLf37koOh9inqf4xFkC+Yi8u72jNS8c6IVkK4aJUh1Ih1vqqIInFDCLAN8sMi5Dlpr9q+mXkY=,iv:yN8ouYsZJ52tyaAWsH3GbHp0gYkwpoas44FhD+VfgIw=,tag:SuPC4L/s8yksg0GXXwH55Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
