apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:tiCddtLyYaNdUuIxWY03jM6LnUcM+hjkXQVwspvf5HMPHLB5iJRYwXJ9QVFMZ/dCBjyUssKqt1agkVZHV6xEE+h01BfXY6o2XW/TWeGSuy5p,iv:CJzytgdo17B9BpMRPOE/M3bcJEEksaF/HZM3jcvgz9Q=,tag:MSz1pU9UK1iYjTpcURIMtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bHQzTXVsYjVRMmxSaVdX
            TURHNE4zL2NLbDlSb3FGNlBOK3lzakdLUG44ClNvVldMcUVmV2p5bVdnbkhnUnZL
            SGt3clZIUTIzUDVtaSs2czE0TkE0RDQKLS0tIG5ZL0ROeDJhTHdnVElrcUwxMjVr
            dXFNNEIxMjdPaks4ZUpEaG92RnJ4VWsKSXnFl+uhgbcg9Ch64kLvnPnHFHfx52mF
            B0cruUbopTDb1PWPfIFHR7oGws4INk4Mas5PLVRWWG4eVPvh7MX4jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T07:12:02Z"
    mac: ENC[AES256_GCM,data:Qx403DJkhbzv6OAA//KkzWVdL7eIov3xl/jKLNQq7HbiHd0ZUsBaHe+vqJQEQeTHP836pibQVz5hOpVymfLxATJJVab2Be4pFYqwhPTLbVmb/+1zzAwcEFg4axMAXaKQwwI4c9S0W+lvnRzUiZD35gKwAp5LbG+RF6aFQ33fwlU=,iv:tg+DIouJAC//KcqMLzehc8xf1FVzSSeWwPQ9iQRazeI=,tag:6tZqBpQdky/r5i2vCqQaSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
