apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BbrwjBwWO+WXr2NAX8g8vqiHgi/lrydn0j4kkVdcrbY=,iv:hgGQMk9/zO/9AtA4mJk2ofOYvquQJYkTv5M0w2dG0vw=,tag:Qei0VvDR9sBIrbbltxdPWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMk1BMVpwblNXUEtPVHZm
            WTRlemM0Ulh4Vi8zOStXRmVvTHpQNk4zTGo4CktOTTdxM2JrNm1HWm9wS21jcisy
            REhEdjNSMFhMMnR3MjRqTmpBbnQvU28KLS0tIEpyTVpDUlBFTnlBdG56QW5jSGxI
            VkVPYlR3bi9HTTJQK2xDaWZtUkV0b00KHRtI7o5uLmvVlXc+6WO3bi1YXYp/Bo8D
            x0Os4gvmqEjhJ/33bJkMuQTCOoSOzraR3GvwT/2WnUyXAz+Q7mBnYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T05:53:26Z"
    mac: ENC[AES256_GCM,data:1N6AHgUw+nGQvy8DBzTK9djVJYduKG5lcdp4w2vmhgkKBlwLn7AHizAmW5zUvV21ciRvQRMdKLQwSuSPbug5LDSPr3jkzjgy4MKkCkjbVLIaJE4PTODKWzbbgsIuEm/0XhqPrIbZXuJ/qXPKCg9UBKPeh/w5Wms3FYQjgE9a7m4=,iv:vPnvaVs/Ixh5z6JSs7Wm3/OCzG2qIU8u9FAZ2g8ZHUA=,tag:FmqoimIla1zeOM23yufG3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
