apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:9nbkyq0rjrKNNXixDo4zcc+8DhebeN4ZJ6YSoA/SP/8=,iv:6AS1qK4pe5YRuC8sqn0HTgPDipOZeHn6j9uYLHGVMa0=,tag:AEbh9SUcCBnlKms3zRgrRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK2xjczJNWlhyN3VDaUtI
            c0FrT0FRdVFabUplU3BlZVBzbmRWdG5nbng4CmlVL0lyTjJscFRPRXJKSE1ucU5V
            YjhFSVhxKzVnUi9qVmh2dDl1dWhaQ0kKLS0tIDF6eWhrNkVMS0Z2VVVhWEVNdjhy
            U0FvK0QyZjhaVU91YVNEcURBK1huMTgK5WbxFwiW8jgJYFWMHdIiY/U4gjakGRBh
            WeiQojdhH7uGg5psIS1924U8HCvuRfUbU7LyxoGFNjr8P57XPBdKvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T16:07:01Z"
    mac: ENC[AES256_GCM,data:Ej9bz2/HBPROG3ck6VR2VyARifVP2wRL+lWDy1rS+zHui51bzX5+Cia7HrxLHaW4UictsUFO3+KoYKjmqpsJ9/Jb+wZae33p3G915verf1GbR3vHzAhyBLHA4f5PDHXpdsaj3UgNMKIhbpEeMGk74OBei14b/quRW6RnDAKx4Og=,iv:DMaUN4cmYPR7pNo3rK/tsVTpiuxJ76o8fdmCZT2ZfLg=,tag:cyXj+vkgrHMa7qh+eFFd2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
