apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:RYVfT1mHf2fYYcyb9ATHkzoVsocTm33UNUkVpRCvvFoEQmedBRv1kA==,iv:xlgowKWbXIzY7QfYsjJrvhyKLvi3urdigZ5zles+Yow=,tag:CkXWigyMIVy+A1ymAbDAew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbjA0WEdqNmE1QnlFbC9B
            ekVXUWFRelVwOHpCR2JpOGhuN3FIZ04xMFRjCmszc0hQS1Jqd3pKUGZkOFZHUEpl
            cVc4b1dpMC91bjJ4dFgzSlJLL1YxNkUKLS0tIHdIWnFFd0lIRUhPNWNraFdDQUsy
            MFdFS1Q4Qk9RTlhUNkY0bGQvZ3c5QlUKkI63C6WexnmeWVehqvX81V5QWdy+OGr5
            kkq8q/ypYF9r3Q2cdwiOO5+5gyxw9O9aeHmbjVdQkpL/QkJJSYQROg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T09:22:14Z"
    mac: ENC[AES256_GCM,data:GKNbvFhccRNGNpeIFTtAe5/R08dDI8eQ/hJQAZeYNMZpQAcRf3qWvPFtcYMbMcE0ejJK6n+cJbe9y4N6Hw+3obxmZdw4o0H8ubg+WxJREqFGgj6hUeHSt3d8NFBXEMoXgspuq36Do39Fg86CCFzpAb/VHe1bXDVuNzY2REy+5To=,iv:J9px0WAgO5n6eHupDapAajFfOQnMVSvyXEs/GKkRfHk=,tag:iB+5JF1LYV6JHMQCle6jtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
