apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:GqrluUJjQIJiYWycNO3HMLRnshMzGyMWm8REpijvZBcbVPDKjpZXyA==,iv:uVlOn8Ri9a2yU35rJYMVaMyPKALbVEirf4IchAoOQ3E=,tag:hWmkZvnfPP3P8hPgNuRCaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wmkk3e59vh4kkw0ardjuhke8guve7qj9wufthfqd7ulz3dnvjadqszypt9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aERZUVpLdnBaSTltbEUr
            UXMzVWlEUVBiMEo4eWZaR0kzeHpsaUNpTGtnCm4wL0JCTHdITk1uSzh3TVRrRlhU
            U2pscmZUcUJyUzlGQ2VPL29IZ2lZT0kKLS0tIDV1THMxYVZIb0YzR2RhZ0RYUVVz
            eVlKYkNicUdXZDkrNTlsNnZmZFJyaFEKH/FPHdygipBL03wjH6/q+lPLL/cJNk6/
            6wlLpcFyMwELcLeuewFKiM4oonbrEEsgja7EceMjs0vNYfOwVDd06g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T11:40:11Z"
    mac: ENC[AES256_GCM,data:fBlC9j8qebaxhm3SNlGR4vu88IPkSxhF1jCuZ8EdCuOMuPZr/p4/eWWjNczcEaBpGwg9lCXBwl6H18HdCNiUI/t1Mx70/ZW/bzVO+Ue6Jk89jNylhs9mnKchor7yx3kviighz2AnL4pL6DRRIU84qnqQtaVjOoqhsHxiPyVPvFA=,iv:GXZe2q2NRI3Q8rwyyqYJTfIOz+hr1+2ipSBwYTJKJBs=,tag:bPq5OYitDfVkrzJZLWAkdg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
